---
services:
  netbox:
    container_name: netbox-sqids-devcontainer
    image: netboxcommunity/netbox:${NETBOX_VARIANT-latest}-devcontainer
    depends_on:
      - postgres
      - redis
    build:
      dockerfile: .devcontainer/Dockerfile-plugin_dev
      context: ..
    env_file:
      - env/netbox.env
      - path: env/local.env
        required: false
    volumes:
      - ../:/opt/netbox-sqids:cached
      - ~/.gitconfig:/home/ubuntu/.gitconfig:z,ro
      - ~/.ssh:/home/ubuntu/.ssh
      - ./home/.config/:/home/ubuntu/.config/
      - ./home/.claude:/home/ubuntu/.claude
      - ./home/.claude.json:/home/ubuntu/.claude.json
      - ./configuration:/etc/netbox/config:z,ro
      - netbox-scripts:/etc/netbox/scripts
    command:
      - sleep
      - infinity

  postgres:
    container_name: netbox-sqids-postgres
    image: postgres:16
    env_file: env/postgres.env
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data

  redis:
    container_name: netbox-sqids-redis
    image: redis:7-alpine
    command:
      - sh
      - -c
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD
    env_file: env/redis.env

volumes:
  netbox-postgres-data:
    driver: local
  netbox-scripts:
    driver: local
